//! Orchestrates rendering into the set of output files emitted by the plugin.

use forge_plugin_sdk::ir;
use forge_plugin_sdk::{GenerationOutput, OutputFile};

use crate::operations::render_client_class;
use crate::runtime::{RUNTIME_TS, TSCONFIG_JSON};
use crate::types::render_models_module;

#[derive(Debug, Clone)]
pub struct Config {
    pub package_name: String,
    pub base_url: Option<String>,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            package_name: "api-client".into(),
            base_url: None,
        }
    }
}

/// Render the full set of TypeScript files for a given IR.
pub fn all(spec: &ir::Ir, cfg: &Config) -> GenerationOutput {
    let base_url = cfg
        .base_url
        .clone()
        .or_else(|| spec.servers.first().map(|s| s.url.clone()))
        .unwrap_or_default();

    let package_json = render_package_json(&cfg.package_name, &spec.info);
    let models_ts = render_models_module(spec);
    let client_ts = render_client_class(spec, &base_url);
    let index_ts = render_index_ts();
    let readme = render_readme(&cfg.package_name, &spec.info);

    let files = vec![
        OutputFile::text("README.md", readme),
        OutputFile::text("package.json", package_json),
        OutputFile::text("src/client.ts", client_ts),
        OutputFile::text("src/index.ts", index_ts),
        OutputFile::text("src/models.ts", models_ts),
        OutputFile::text("src/runtime.ts", RUNTIME_TS),
        OutputFile::text("tsconfig.json", TSCONFIG_JSON),
    ];

    GenerationOutput {
        files,
        diagnostics: vec![],
    }
}

fn render_package_json(name: &str, info: &ir::ApiInfo) -> String {
    let escaped_name = escape_json(name);
    let escaped_version = escape_json(&info.version);
    let escaped_title = escape_json(&info.title);
    format!(
        "{{\n  \"name\": \"{escaped_name}\",\n  \"version\": \"{escaped_version}\",\n  \"description\": \"Generated TypeScript client for {escaped_title}\",\n  \"type\": \"module\",\n  \"main\": \"src/index.ts\",\n  \"types\": \"src/index.ts\",\n  \"sideEffects\": false\n}}\n"
    )
}

fn render_index_ts() -> String {
    let mut s = String::new();
    s.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    s.push_str("export * from \"./client.js\";\n");
    s.push_str("export * from \"./models.js\";\n");
    s.push_str("export { ApiError } from \"./runtime.js\";\n");
    s.push_str("export type { RequestOptions } from \"./runtime.js\";\n");
    s
}

fn render_readme(name: &str, info: &ir::ApiInfo) -> String {
    let mut s = String::new();
    s.push_str(&format!("# {}\n\n", info.title));
    if let Some(d) = &info.description {
        s.push_str(d);
        s.push_str("\n\n");
    }
    s.push_str(&format!(
        "Generated TypeScript client for `{}` v{}.\n",
        info.title, info.version
    ));
    s.push_str(&format!("Package name: `{}`.\n\n", name));
    s.push_str("## Usage\n\n```ts\nimport { ApiClient } from \"./src/index.js\";\n\nconst client = new ApiClient({ baseUrl: \"https://example.com\" });\n```\n\n");
    s.push_str("Generated by [openapi-forge](https://github.com/marcusdunn/openapi-forge).\n");
    s
}

fn escape_json(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
