//! IR `Operation` → TypeScript method source.

use forge_plugin_sdk::ir;

use crate::naming::ts_ident;
use crate::types::render_type_ref;

/// Render the entire `client.ts` source.
pub fn render_client_class(spec: &ir::Ir, default_base_url: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    s.push_str(
        "import {\n  ApiError,\n  JSON_HEADERS,\n  RequestOptions,\n  appendQuery,\n  appendQueryDeepObject,\n  appendQueryDelimited,\n  appendQueryForm,\n  joinUrl,\n} from \"./runtime.js\";\n",
    );
    s.push_str("import type { BinaryData } from \"./runtime.js\";\n");
    s.push_str("import type * as M from \"./models.js\";\n\n");

    if !spec.security_schemes.is_empty() {
        s.push_str(&render_auth_config_type(spec));
    }

    s.push_str("export interface ApiClientOptions {\n");
    s.push_str("  baseUrl?: string;\n");
    s.push_str("  defaultHeaders?: Record<string, string>;\n");
    s.push_str("  fetch?: typeof fetch;\n");
    if !spec.security_schemes.is_empty() {
        s.push_str("  auth?: AuthConfig;\n");
    }
    s.push_str("}\n\n");

    s.push_str("export class ApiClient {\n");
    s.push_str("  readonly baseUrl: string;\n");
    s.push_str("  readonly defaultHeaders: Record<string, string>;\n");
    s.push_str("  private readonly _fetch: typeof fetch;\n");
    if !spec.security_schemes.is_empty() {
        s.push_str("  private readonly _auth: AuthConfig | undefined;\n");
    }
    s.push('\n');
    s.push_str(&format!(
        "  constructor(opts: ApiClientOptions = {{}}) {{\n    this.baseUrl = opts.baseUrl ?? {};\n    this.defaultHeaders = opts.defaultHeaders ?? {{}};\n    this._fetch = opts.fetch ?? fetch;\n",
        json_string_literal(default_base_url),
    ));
    if !spec.security_schemes.is_empty() {
        s.push_str("    this._auth = opts.auth;\n");
    }
    s.push_str("  }\n\n");
    for op in &spec.operations {
        s.push_str(&render_operation(spec, op));
        s.push('\n');
    }
    s.push_str("}\n");
    s
}

fn render_auth_config_type(spec: &ir::Ir) -> String {
    let mut variants: Vec<&'static str> = Vec::new();
    for scheme in &spec.security_schemes {
        match &scheme.kind {
            ir::SecuritySchemeKind::ApiKey(_) => {
                if !variants.contains(&"apiKey") {
                    variants.push("apiKey");
                }
            }
            ir::SecuritySchemeKind::HttpBearer { .. } => {
                if !variants.contains(&"bearer") {
                    variants.push("bearer");
                }
            }
            ir::SecuritySchemeKind::HttpBasic => {
                if !variants.contains(&"basic") {
                    variants.push("basic");
                }
            }
            // `oauth2` (since PR #69) and `openIdConnect` (still rejected
            // at parse time) reach this generator without dedicated
            // auth-injection code — library consumers are expected to
            // run the OAuth flow themselves and pass the resulting
            // bearer token via the existing bearer arm if applicable.
            // The standalone `generator-typescript-cli` is where login
            // logic lives.
            // mTLS auth happens at the transport layer; consumers wire
            // up client certificates against fetch / Node tls themselves.
            ir::SecuritySchemeKind::Oauth2(_)
            | ir::SecuritySchemeKind::OpenIdConnect { .. }
            | ir::SecuritySchemeKind::MutualTls => {}
        }
    }
    if variants.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("export type AuthConfig =\n");
    for (i, v) in variants.iter().enumerate() {
        let line = match *v {
            "apiKey" => "  | { kind: \"apiKey\"; key: string }",
            "bearer" => "  | { kind: \"bearer\"; token: string }",
            "basic" => "  | { kind: \"basic\"; username: string; password: string }",
            _ => unreachable!(),
        };
        s.push_str(line);
        if i + 1 == variants.len() {
            s.push(';');
        }
        s.push('\n');
    }
    s.push('\n');
    s
}

/// Render one method, including JSDoc.
pub fn render_operation(spec: &ir::Ir, op: &ir::Operation) -> String {
    let mut s = String::new();
    let body_pick = pick_body(spec, op);
    let response_pick = pick_response(spec, op);

    let docs = op.documentation.as_deref();
    let error_responses: Vec<(String, String)> = collect_error_response_types(spec, op);
    let needs_jsdoc = docs.is_some()
        || !op.tags.is_empty()
        || !error_responses.is_empty()
        || matches!(response_pick, ResponsePick::Raw { .. });
    if needs_jsdoc {
        s.push_str("  /**\n");
        if let Some(d) = docs {
            for line in d.lines() {
                s.push_str(&format!("   * {line}\n"));
            }
        }
        if !op.tags.is_empty() {
            s.push_str(&format!("   * @tags {}\n", op.tags.join(", ")));
        }
        if let ResponsePick::Raw { media_type } = &response_pick {
            s.push_str(&format!(
                "   * Returns the raw `Response`; the body media type is `{media_type}`. \
                 Caller drives stream / decode.\n"
            ));
        }
        for (status, ts_type) in &error_responses {
            s.push_str(&format!(
                "   * @throws {{ApiError}} status `{status}` body: `{ts_type}`\n"
            ));
        }
        s.push_str("   */\n");
    }
    let method_name = ts_ident(&op.id);
    let return_type = response_pick.return_type();

    let params = render_param_list(spec, op, body_pick.as_ref());
    s.push_str(&format!(
        "  async {method_name}({params}): Promise<{return_type}> {{\n",
    ));

    // URL build, with array-aware path templates.
    s.push_str(&format!(
        "    let url = joinUrl(this.baseUrl, {});\n",
        render_path_template(spec, &op.path_template, &op.path_params),
    ));

    // Query string assembly — one helper call per param, picked by style.
    s.push_str(&render_query_assembly(spec, op));

    // Headers
    s.push_str("    const headers: Record<string, string> = { ...this.defaultHeaders");
    if body_pick.as_ref().is_some_and(|b| b.kind.is_json()) {
        s.push_str(", ...JSON_HEADERS");
    }
    s.push_str(", ...(options?.headers ?? {}) };\n");
    s.push_str(&render_header_injection(spec, op));
    s.push_str(&render_cookie_injection(spec, op));

    // Auth: try each declared security requirement; the first one whose
    // scheme matches the configured auth wins.
    let auth_block = render_auth_block(spec, op);
    if !auth_block.is_empty() {
        s.push_str(&auth_block);
    }

    // Body construction (pre-init), and return the expression to assign to
    // `init.body`. Empty when there's no body.
    let (body_construction, body_init_expr) = match body_pick.as_ref() {
        Some(b) => render_body_construction(spec, b),
        None => (String::new(), String::new()),
    };
    s.push_str(&body_construction);
    if let Some(b) = body_pick.as_ref() {
        if let Some(ct) = b.kind.explicit_content_type() {
            s.push_str(&format!(
                "    headers[\"Content-Type\"] = {};\n",
                json_string_literal(ct)
            ));
        }
    }

    s.push_str("    const init: RequestInit = {\n");
    s.push_str(&format!("      method: \"{}\",\n", op.method.as_str()));
    s.push_str("      headers,\n");
    s.push_str("      signal: options?.signal,\n");
    if !body_init_expr.is_empty() {
        s.push_str(&format!("      body: {body_init_expr},\n"));
    }
    s.push_str("    };\n");
    s.push_str("    const res = await this._fetch(url, init);\n");
    s.push_str("    if (!res.ok) throw await ApiError.fromResponse(res);\n");

    match &response_pick {
        ResponsePick::Void => s.push_str("    return;\n"),
        ResponsePick::Raw { .. } => s.push_str("    return res;\n"),
        ResponsePick::Json(_) => s.push_str(&format!(
            "    return (await res.json()) as {return_type};\n"
        )),
    }

    s.push_str("  }\n");
    s
}

/// Generate the auth-injection block for one operation. Returns an empty
/// string when no security applies. Emits a sequence of `if/else if`
/// branches in declaration order; the first that matches the configured
/// `auth.kind` wins (any-of semantics, with first-match-by-kind).
fn render_auth_block(spec: &ir::Ir, op: &ir::Operation) -> String {
    if op.security.is_empty() {
        return String::new();
    }
    let mut branches: Vec<Branch> = Vec::new();
    for req in &op.security {
        let Some(scheme) = spec.security_schemes.iter().find(|s| s.id == req.scheme_id) else {
            continue;
        };
        let body = match &scheme.kind {
            ir::SecuritySchemeKind::ApiKey(api) => {
                let header_name = json_string_literal(&api.name);
                let inject = match api.location {
                    ir::ApiKeyLocation::Header => {
                        format!("      headers[{header_name}] = this._auth.key;\n")
                    }
                    ir::ApiKeyLocation::Query => format!(
                        "      url = appendQuery(url, {{ {header_name}: this._auth.key }});\n"
                    ),
                    ir::ApiKeyLocation::Cookie => format!(
                        "      headers[\"Cookie\"] = `{name}=${{encodeURIComponent(this._auth.key)}}`;\n",
                        name = api.name.replace('`', "")
                    ),
                };
                Some(("apiKey", inject))
            }
            ir::SecuritySchemeKind::HttpBearer { .. } => Some((
                "bearer",
                "      headers[\"Authorization\"] = `Bearer ${this._auth.token}`;\n".to_string(),
            )),
            ir::SecuritySchemeKind::HttpBasic => Some((
                "basic",
                "      headers[\"Authorization\"] = `Basic ${btoa(`${this._auth.username}:${this._auth.password}`)}`;\n".to_string(),
            )),
            // No per-op auth injection for oauth2 / openIdConnect / mTLS;
            // the library's consumer runs the flow externally (oauth2 /
            // openIdConnect) or wires up client certificates at the
            // transport layer (mTLS) and the bearer arm carries any
            // resulting token.
            ir::SecuritySchemeKind::Oauth2(_)
            | ir::SecuritySchemeKind::OpenIdConnect { .. }
            | ir::SecuritySchemeKind::MutualTls => None,
        };
        if let Some((kind, body)) = body {
            branches.push(Branch {
                kind: kind.to_string(),
                scheme_id: scheme.id.clone(),
                body,
            });
        }
    }
    if branches.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    for (i, b) in branches.iter().enumerate() {
        if i == 0 {
            s.push_str("    if (");
        } else {
            s.push_str(" else if (");
        }
        s.push_str(&format!(
            "this._auth?.kind === \"{}\") /* scheme: {} */ {{\n{}    }}",
            b.kind, b.scheme_id, b.body
        ));
    }
    s.push('\n');
    s
}

struct Branch {
    kind: String,
    scheme_id: String,
    body: String,
}

fn render_param_list(
    spec: &ir::Ir,
    op: &ir::Operation,
    body_pick: Option<&BodyPick<'_>>,
) -> String {
    let mut required: Vec<String> = Vec::new();
    let mut optional: Vec<(String, String)> = Vec::new();

    for p in &op.path_params {
        // Path params are always required by OpenAPI rule.
        required.push(format!(
            "{}: {}",
            ts_ident(&p.name),
            render_type_ref(spec, &p.r#type, Some("M"))
        ));
    }
    for p in op
        .query_params
        .iter()
        .chain(op.header_params.iter())
        .chain(op.cookie_params.iter())
    {
        let ts = render_type_ref(spec, &p.r#type, Some("M"));
        if p.required {
            required.push(format!("{}: {}", ts_ident(&p.name), ts));
        } else {
            optional.push((ts_ident(&p.name), format!("{} | undefined", ts)));
        }
    }

    if let Some(b) = body_pick {
        if b.required {
            required.push(format!("body: {}", b.ts_type));
        } else {
            optional.push(("body".into(), format!("{} | undefined", b.ts_type)));
        }
    }

    let mut all = required.clone();
    for (n, t) in &optional {
        all.push(format!("{n}?: {t}"));
    }
    all.push("options?: RequestOptions".into());

    all.join(", ")
}

// ---- body selection ------------------------------------------------------

/// Categorisation of the picked request-body content entry. Drives both the
/// method-signature TS type and the runtime body-construction code.
enum BodyKind {
    Json,
    UrlEncoded,
    Multipart,
    OctetStream,
    /// `text/*` — value is the full media type so we can echo it back as
    /// `Content-Type`.
    Text(String),
    /// Anything else (`application/cbor`, custom types). We pass the body
    /// through as-is and set `Content-Type` to the declared media type.
    Other(String),
}

impl BodyKind {
    fn is_json(&self) -> bool {
        matches!(self, BodyKind::Json)
    }

    /// `Content-Type` to set explicitly. `None` means "leave it to fetch /
    /// the runtime / defaults" — JSON uses `JSON_HEADERS` already, multipart
    /// must be left alone so fetch can add the boundary.
    fn explicit_content_type(&self) -> Option<&str> {
        match self {
            BodyKind::Json | BodyKind::Multipart => None,
            BodyKind::UrlEncoded => Some("application/x-www-form-urlencoded"),
            BodyKind::OctetStream => Some("application/octet-stream"),
            BodyKind::Text(mt) | BodyKind::Other(mt) => Some(mt),
        }
    }
}

struct BodyPick<'a> {
    content: &'a ir::BodyContent,
    kind: BodyKind,
    required: bool,
    ts_type: String,
}

/// Pick the request body's primary content entry. Preference order: JSON,
/// urlencoded, multipart, octet-stream, then any `text/*`, then the first
/// declared entry. The IR keeps every declared content type around; the TS
/// generator picks one because methods take exactly one `body` argument.
fn pick_body<'a>(spec: &'a ir::Ir, op: &'a ir::Operation) -> Option<BodyPick<'a>> {
    let body = op.request_body.as_ref()?;
    type KindFactory = fn() -> BodyKind;
    let preferences: &[(&str, KindFactory)] = &[
        ("application/json", || BodyKind::Json),
        ("application/x-www-form-urlencoded", || BodyKind::UrlEncoded),
        ("multipart/form-data", || BodyKind::Multipart),
        ("application/octet-stream", || BodyKind::OctetStream),
    ];
    for (mt, factory) in preferences {
        if let Some(c) = body.content.iter().find(|c| c.media_type == *mt) {
            let kind = factory();
            let ts_type = match &kind {
                BodyKind::OctetStream => "BinaryData".to_string(),
                _ => render_type_ref(spec, &c.r#type, Some("M")),
            };
            return Some(BodyPick {
                content: c,
                kind,
                required: body.required,
                ts_type,
            });
        }
    }
    if let Some(c) = body
        .content
        .iter()
        .find(|c| c.media_type.starts_with("text/"))
    {
        return Some(BodyPick {
            content: c,
            kind: BodyKind::Text(c.media_type.clone()),
            required: body.required,
            ts_type: "string".to_string(),
        });
    }
    body.content.first().map(|c| BodyPick {
        content: c,
        kind: BodyKind::Other(c.media_type.clone()),
        required: body.required,
        ts_type: "BinaryData".to_string(),
    })
}

// ---- response selection --------------------------------------------------

enum ResponsePick {
    Void,
    /// Non-JSON 2xx — return the raw `Response`.
    Raw {
        media_type: String,
    },
    /// Union of JSON 2xx body types (and `void` for status-only responses).
    Json(String),
}

impl ResponsePick {
    fn return_type(&self) -> String {
        match self {
            ResponsePick::Void => "void".into(),
            ResponsePick::Raw { .. } => "Response".into(),
            ResponsePick::Json(t) => t.clone(),
        }
    }
}

/// Pick the response shape. JSON-only 2xx responses fold into a union; if
/// any 2xx response declares a non-JSON body the method returns `Response`
/// so the caller can drive streaming or other decode strategies.
fn pick_response(spec: &ir::Ir, op: &ir::Operation) -> ResponsePick {
    let mut union: Vec<String> = Vec::new();
    let mut had_success_no_body = false;
    let mut non_json_media: Option<String> = None;
    for r in &op.responses {
        let is_success = match r.status {
            ir::ResponseStatus::Explicit { code } => (200..300).contains(&code),
            ir::ResponseStatus::Range { class } => class == 2,
            ir::ResponseStatus::Default => false,
        };
        if !is_success {
            continue;
        }
        if r.content.is_empty() {
            had_success_no_body = true;
            continue;
        }
        if let Some(c) = r
            .content
            .iter()
            .find(|c| c.media_type == "application/json")
        {
            let ts = render_type_ref(spec, &c.r#type, Some("M"));
            if !union.iter().any(|x| x == &ts) {
                union.push(ts);
            }
        } else if non_json_media.is_none() {
            non_json_media = Some(r.content[0].media_type.clone());
        }
    }
    if union.is_empty() {
        return match non_json_media {
            Some(media_type) => ResponsePick::Raw { media_type },
            None => ResponsePick::Void,
        };
    }
    if had_success_no_body && !union.iter().any(|x| x == "void") {
        union.push("void".into());
    }
    ResponsePick::Json(union.join(" | "))
}

/// Collect error responses (default + non-2xx) with a JSON body so they
/// can be referenced in JSDoc. Each entry is `(status_label, ts_type)`.
fn collect_error_response_types(spec: &ir::Ir, op: &ir::Operation) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();
    for r in &op.responses {
        let is_error = match r.status {
            ir::ResponseStatus::Explicit { code } => !(200..300).contains(&code),
            ir::ResponseStatus::Range { class } => class != 2,
            ir::ResponseStatus::Default => true,
        };
        if !is_error {
            continue;
        }
        let Some(c) = r
            .content
            .iter()
            .find(|c| c.media_type == "application/json")
        else {
            continue;
        };
        let label = match r.status {
            ir::ResponseStatus::Explicit { code } => code.to_string(),
            ir::ResponseStatus::Range { class } => format!("{class}XX"),
            ir::ResponseStatus::Default => "default".into(),
        };
        let ts = render_type_ref(spec, &c.r#type, Some("M"));
        out.push((label, ts));
    }
    out
}

/// Convert `/pets/{petId}/photos/{photoId}` into a TS template literal.
/// Array-typed path params with `simple` style are comma-joined; everything
/// else passes through `encodeURIComponent(String(value))`.
fn render_path_template(spec: &ir::Ir, template: &str, path_params: &[ir::Parameter]) -> String {
    let mut out = String::from("`");
    let bytes = template.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'{' {
            if let Some(close) = template[i..].find('}') {
                let raw = &template[i + 1..i + close];
                let var = ts_ident(raw);
                let is_array = path_params
                    .iter()
                    .find(|p| p.name == raw)
                    .map(|p| param_is_array(spec, &p.r#type))
                    .unwrap_or(false);
                if is_array {
                    out.push_str(&format!(
                        "${{({var} as ReadonlyArray<unknown>).map((v) => encodeURIComponent(String(v))).join(\",\")}}"
                    ));
                } else {
                    out.push_str(&format!("${{encodeURIComponent(String({var}))}}"));
                }
                i += close + 1;
                continue;
            }
        }
        let ch = bytes[i] as char;
        if ch == '`' || ch == '\\' || ch == '$' {
            out.push('\\');
        }
        out.push(ch);
        i += 1;
    }
    out.push('`');
    out
}

/// Pick the right `appendQuery*` helper per parameter style. Falls back to
/// `appendQueryForm` for anything we don't have a dedicated helper for.
fn render_query_assembly(spec: &ir::Ir, op: &ir::Operation) -> String {
    if op.query_params.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    for p in &op.query_params {
        let key = json_string_literal(&p.name);
        let var = ts_ident(&p.name);
        let style = p.style.unwrap_or(ir::ParameterStyle::Form);
        match style {
            ir::ParameterStyle::Form => {
                let explode = if p.explode { "true" } else { "false" };
                s.push_str(&format!(
                    "    url = appendQueryForm(url, {key}, {var}, {explode});\n"
                ));
            }
            ir::ParameterStyle::PipeDelimited => {
                s.push_str(&format!(
                    "    url = appendQueryDelimited(url, {key}, {var} as ReadonlyArray<unknown> | undefined, \"|\");\n"
                ));
            }
            ir::ParameterStyle::SpaceDelimited => {
                s.push_str(&format!(
                    "    url = appendQueryDelimited(url, {key}, {var} as ReadonlyArray<unknown> | undefined, \" \");\n"
                ));
            }
            ir::ParameterStyle::DeepObject => {
                s.push_str(&format!(
                    "    url = appendQueryDeepObject(url, {key}, {var} as Record<string, unknown> | undefined);\n"
                ));
            }
            // Anything else falls back to form encoding with an inline
            // comment naming the unhandled style. The parser already emits
            // a W-PARAM-STYLE-UNSUPPORTED warning when this happens for a
            // location it doesn't fit.
            _ => {
                let _ = spec; // unused but kept for signature symmetry
                s.push_str(&format!(
                    "    url = appendQueryForm(url, {key}, {var}, true); /* unhandled style: {style:?} */\n"
                ));
            }
        }
    }
    s
}

/// Per-header injection. Array-typed values comma-join.
fn render_header_injection(spec: &ir::Ir, op: &ir::Operation) -> String {
    let mut s = String::new();
    for p in &op.header_params {
        let var = ts_ident(&p.name);
        let key = json_string_literal(&p.name);
        let is_array = param_is_array(spec, &p.r#type);
        let assignment = if is_array {
            format!(
                "headers[{key}] = ({var} as ReadonlyArray<unknown>).map((v) => String(v)).join(\",\");\n"
            )
        } else {
            format!("headers[{key}] = String({var});\n")
        };
        if p.required {
            s.push_str("    ");
            s.push_str(&assignment);
        } else {
            s.push_str(&format!(
                "    if ({var} !== undefined && {var} !== null) {assignment}"
            ));
        }
    }
    s
}

/// Cookie params get assembled into a single `Cookie:` header. Skip
/// undefined values; required params are always included.
fn render_cookie_injection(spec: &ir::Ir, op: &ir::Operation) -> String {
    if op.cookie_params.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("    {\n      const _cookies: string[] = [];\n");
    for p in &op.cookie_params {
        let var = ts_ident(&p.name);
        let name_lit = json_string_literal(&p.name);
        let is_array = param_is_array(spec, &p.r#type);
        // Cookies use `form` style by default; arrays comma-join (explode=false
        // is the only sane request-side interpretation).
        let value_expr = if is_array {
            format!(
                "({var} as ReadonlyArray<unknown>).map((v) => encodeURIComponent(String(v))).join(\",\")"
            )
        } else {
            format!("encodeURIComponent(String({var}))")
        };
        let push = format!("        _cookies.push(`${{{name_lit}}}=${{{value_expr}}}`);\n");
        if p.required {
            s.push_str(&push);
        } else {
            s.push_str(&format!(
                "      if ({var} !== undefined && {var} !== null) {{\n  {push}      }}\n",
            ));
        }
    }
    s.push_str(
        "      if (_cookies.length > 0) headers[\"Cookie\"] = _cookies.join(\"; \");\n    }\n",
    );
    s
}

/// Build the body-construction code and the expression that goes into
/// `init.body`. Empty strings when the picked body kind doesn't need
/// pre-init wiring (e.g. octet-stream just passes the body through).
fn render_body_construction(spec: &ir::Ir, body: &BodyPick<'_>) -> (String, String) {
    match &body.kind {
        BodyKind::Json => (String::new(), "JSON.stringify(body)".to_string()),
        BodyKind::OctetStream | BodyKind::Other(_) => {
            (String::new(), "body as BodyInit".to_string())
        }
        BodyKind::Text(_) => (String::new(), "body".to_string()),
        BodyKind::UrlEncoded => {
            let mut s = String::new();
            s.push_str("    const _form = new URLSearchParams();\n");
            for prop in body_properties(spec, body.content) {
                let key = json_string_literal(&prop.name);
                let access = property_access("body", &prop.name);
                let is_array = param_is_array(spec, &prop.r#type);
                if is_array {
                    s.push_str(&format!(
                        "    if ({access} !== undefined && {access} !== null) for (const v of {access}) _form.append({key}, String(v));\n"
                    ));
                } else {
                    s.push_str(&format!(
                        "    if ({access} !== undefined && {access} !== null) _form.append({key}, String({access}));\n"
                    ));
                }
            }
            (s, "_form".to_string())
        }
        BodyKind::Multipart => {
            let mut s = String::new();
            s.push_str("    const _form = new FormData();\n");
            for prop in body_properties(spec, body.content) {
                let key = json_string_literal(&prop.name);
                let access = property_access("body", &prop.name);
                let is_binary = param_is_binary(spec, &prop.r#type);
                let value_expr = if is_binary {
                    format!("{access} as Blob")
                } else {
                    format!("String({access})")
                };
                let is_array = param_is_array(spec, &prop.r#type);
                if is_array {
                    s.push_str(&format!(
                        "    if ({access} !== undefined && {access} !== null) for (const v of {access}) _form.append({key}, String(v));\n"
                    ));
                } else {
                    s.push_str(&format!(
                        "    if ({access} !== undefined && {access} !== null) _form.append({key}, {value_expr});\n"
                    ));
                }
            }
            (s, "_form".to_string())
        }
    }
}

/// Look up the body schema and yield its declared properties. Returns an
/// empty iterator when the body's referenced type isn't an object — the
/// caller then emits no per-property writes (caller is expected to pass
/// a pre-built `URLSearchParams` / `FormData` via the body argument; not
/// supported by the typed signature, so an empty form is the safe default).
fn body_properties<'a>(spec: &'a ir::Ir, content: &'a ir::BodyContent) -> Vec<&'a ir::Property> {
    let Some(nt) = spec.types.iter().find(|t| t.id == content.r#type) else {
        return Vec::new();
    };
    match &nt.definition {
        ir::TypeDef::Object(o) => o.properties.iter().collect(),
        _ => Vec::new(),
    }
}

fn property_access(receiver: &str, property: &str) -> String {
    if is_safe_ident(property) {
        format!("{receiver}.{property}")
    } else {
        format!("{receiver}[{}]", json_string_literal(property))
    }
}

fn is_safe_ident(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap();
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn param_is_array(spec: &ir::Ir, type_ref: &ir::TypeRef) -> bool {
    spec.types
        .iter()
        .find(|t| t.id == *type_ref)
        .map(|nt| matches!(&nt.definition, ir::TypeDef::Array(_)))
        .unwrap_or(false)
}

fn param_is_binary(spec: &ir::Ir, type_ref: &ir::TypeRef) -> bool {
    // Per #105: binary signal is `String` + `format_extension: byte|binary`.
    spec.types
        .iter()
        .find(|t| t.id == *type_ref)
        .and_then(|nt| match &nt.definition {
            ir::TypeDef::Primitive(p) => Some(p),
            _ => None,
        })
        .map(|p| {
            matches!(p.kind, ir::PrimitiveKind::String)
                && matches!(
                    p.constraints.format_extension.as_deref(),
                    Some("byte" | "binary")
                )
        })
        .unwrap_or(false)
}

fn json_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
