//! Static TypeScript files embedded in the generated client.
//!
//! Kept as `&'static str` so the plugin needs no I/O at runtime.

pub const RUNTIME_TS: &str = r#"// Generated by openapi-forge — do not edit by hand.

export interface RequestOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

/// Permissive union for OAS `format: byte` (base64-encoded `string`) and
/// `format: binary` (raw bytes). Generated methods accept any of these
/// and pass them through to `fetch` as-is in the binary body / multipart
/// path; in JSON contexts the user is responsible for pre-encoding to a
/// `string`.
export type BinaryData = string | Blob | ArrayBuffer | Uint8Array;

export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(status: number, body: unknown, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }

  static async fromResponse(res: Response): Promise<ApiError> {
    let body: unknown = null;
    try {
      body = await res.json();
    } catch {
      try {
        body = await res.text();
      } catch {
        body = null;
      }
    }
    return new ApiError(res.status, body, `HTTP ${res.status} ${res.statusText}`);
  }
}

export const JSON_HEADERS: Record<string, string> = { "content-type": "application/json" };

export function joinUrl(baseUrl: string, path: string): string {
  if (baseUrl.length === 0) return path;
  if (baseUrl.endsWith("/") && path.startsWith("/")) return baseUrl + path.slice(1);
  if (!baseUrl.endsWith("/") && !path.startsWith("/")) return baseUrl + "/" + path;
  return baseUrl + path;
}

export function appendQuery(url: string, params: Record<string, unknown>): string {
  let out = url;
  for (const [k, v] of Object.entries(params)) {
    out = appendQueryForm(out, k, v, true);
  }
  return out;
}

/// `style: form`. `explode: true` repeats the key per array item;
/// `explode: false` joins with a comma. Scalars and `undefined`/`null`
/// follow the obvious rules.
export function appendQueryForm(
  url: string,
  key: string,
  value: unknown,
  explode: boolean,
): string {
  if (value === undefined || value === null) return url;
  if (Array.isArray(value)) {
    if (value.length === 0) return url;
    if (explode) {
      const parts = value.map(
        (v) => `${encodeURIComponent(key)}=${encodeURIComponent(String(v))}`,
      );
      return appendRaw(url, parts.join("&"));
    }
    const joined = value.map((v) => encodeURIComponent(String(v))).join(",");
    return appendRaw(url, `${encodeURIComponent(key)}=${joined}`);
  }
  return appendRaw(
    url,
    `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`,
  );
}

/// `style: pipeDelimited` / `spaceDelimited`. Single key, joined value.
export function appendQueryDelimited(
  url: string,
  key: string,
  values: readonly unknown[] | null | undefined,
  delimiter: string,
): string {
  if (!values || values.length === 0) return url;
  const joined = values.map((v) => encodeURIComponent(String(v))).join(delimiter);
  return appendRaw(url, `${encodeURIComponent(key)}=${joined}`);
}

/// `style: deepObject`. Bracket-flattened object: `?k[a]=1&k[b]=2`.
export function appendQueryDeepObject(
  url: string,
  key: string,
  value: Record<string, unknown> | null | undefined,
): string {
  if (!value) return url;
  let out = url;
  for (const [k, v] of Object.entries(value)) {
    if (v === undefined || v === null) continue;
    out = appendRaw(
      out,
      `${encodeURIComponent(`${key}[${k}]`)}=${encodeURIComponent(String(v))}`,
    );
  }
  return out;
}

function appendRaw(url: string, suffix: string): string {
  const sep = url.includes("?") ? "&" : "?";
  return url + sep + suffix;
}
"#;

pub const TSCONFIG_JSON: &str = r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022", "DOM"],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "noEmit": true,
    "isolatedModules": true,
    "declaration": true
  },
  "include": ["src/**/*.ts"]
}
"#;
