//! IR `TypeDef` → TypeScript text.
//!
//! Two entry points: [`render_type_ref`] inlines a reference at a use site
//! (`x: number`, `x: Pet`); [`render_models_module`] emits all the named
//! composite types as a complete `models.ts` source file.

use forge_plugin_sdk::ir;
use forge_plugin_sdk::peel_nullable;

use crate::naming::ts_type_name;

/// Render a `TypeRef` at a use site (e.g. `: string`, `: Pet`).
///
/// `namespace`, if `Some`, is prepended to composite type references —
/// callers in `client.ts` pass `Some("M")` because they import models via
/// `import type * as M from "./models.js"`. Calls inside `models.ts` pass
/// `None` so the references stay unqualified.
pub fn render_type_ref(spec: &ir::Ir, type_ref: &ir::TypeRef, namespace: Option<&str>) -> String {
    // The canonical `T | null` shape (issue #107) is a two-variant Union
    // with the Null singleton — peel it here so every call-site renders
    // `T | null` without each generator branch having to know.
    if let Some(inner) = peel_nullable(&spec.types, type_ref) {
        return format!("{} | null", render_type_ref(spec, inner, namespace));
    }
    let Some(nt) = spec.types.iter().find(|nt| nt.id == *type_ref) else {
        return "unknown /* unresolved type-ref */".into();
    };
    match &nt.definition {
        ir::TypeDef::Primitive(p) => primitive_ts(p),
        ir::TypeDef::Object(_)
        | ir::TypeDef::Array(_)
        | ir::TypeDef::EnumString(_)
        | ir::TypeDef::EnumInt(_)
        | ir::TypeDef::Union(_) => match namespace {
            Some(ns) => format!("{ns}.{}", named_ref(nt)),
            None => named_ref(nt),
        },
        // The bare Null type renders as the TS literal `null`.
        ir::TypeDef::Null => "null".into(),
    }
}

/// PascalCase reference name for a composite type. Prefers `original_name`,
/// falls back to `id`.
pub fn named_ref(nt: &ir::NamedType) -> String {
    let raw = nt.original_name.as_deref().unwrap_or(&nt.id);
    ts_type_name(raw)
}

fn primitive_ts(p: &ir::PrimitiveType) -> String {
    // Per #105 the IR carries the JSON Schema `type` value only; the
    // OAS `format` lands in `format_extension`. JS doesn't distinguish
    // int widths, so all integers/numbers collapse to `number`. The
    // binary-encoding formats get the dedicated `BinaryData` runtime
    // helper.
    let fmt = p.constraints.format_extension.as_deref();
    match (p.kind, fmt) {
        // `byte` (base64) and `binary` (raw octets) both fold to
        // `BinaryData` (defined in runtime.ts: a permissive union of
        // every shape `fetch` accepts plus `string` for the base64
        // case).
        (ir::PrimitiveKind::String, Some("byte" | "binary")) => "BinaryData".into(),
        // Date / date-time / uuid / uri / email / password / decimal /
        // … all fold to `string` for v1. Strongly-typed mappings
        // (Date object, decimal.js, etc.) would be a runtime / config
        // choice for downstream generators.
        (ir::PrimitiveKind::String, _) => "string".into(),
        (ir::PrimitiveKind::Integer, _) | (ir::PrimitiveKind::Number, _) => "number".into(),
        (ir::PrimitiveKind::Bool, _) => "boolean".into(),
    }
}

/// Emit `models.ts`: every composite named type as an `export interface`
/// or `export type` alias.
pub fn render_models_module(spec: &ir::Ir) -> String {
    let mut body = String::new();
    let mut emitted = 0usize;
    for nt in &spec.types {
        if let Some(s) = render_named_type(spec, nt) {
            body.push_str(&s);
            body.push('\n');
            emitted += 1;
        }
    }
    if emitted == 0 {
        body.push_str("export {};\n");
    }
    // `BinaryData` is rendered for `string` properties whose
    // `formatExtension` is `byte` or `binary`. The type itself lives in
    // runtime.ts, so models.ts needs a corresponding import whenever it
    // references the name. A textual scan keeps the dependency
    // detection out of the per-type code paths.
    let mut out = String::new();
    out.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    if body.contains("BinaryData") {
        out.push_str("import type { BinaryData } from \"./runtime.js\";\n\n");
    }
    out.push_str(&body);
    out
}

/// Render a top-level type declaration. Returns `None` for primitives,
/// which are inlined at every use site.
pub fn render_named_type(spec: &ir::Ir, nt: &ir::NamedType) -> Option<String> {
    // The canonical `T | null` Union (issue #107) emits as a `type X = T |
    // null;` alias rather than going through `render_union`'s body
    // machinery.
    if peel_nullable(&spec.types, &nt.id).is_some() {
        let name = named_ref(nt);
        let mut s = String::new();
        if let Some(d) = &nt.description {
            s.push_str(&jsdoc(d, ""));
        }
        let body = render_type_ref(spec, &nt.id, None);
        s.push_str(&format!("export type {name} = {body};\n"));
        return Some(s);
    }
    match &nt.definition {
        ir::TypeDef::Primitive(_) => None,
        ir::TypeDef::Object(o) => {
            // Map shape: empty properties + typed additional
            // properties. Issue #109 collapsed MapType into this
            // canonical Object form; render as a `Record`-like alias.
            if let Some(values_ref) = as_map(o) {
                Some(render_map_alias(spec, nt, values_ref))
            } else {
                Some(render_object(spec, nt, o))
            }
        }
        ir::TypeDef::Array(a) => Some(render_array_alias(spec, nt, a)),
        ir::TypeDef::EnumString(e) => Some(render_enum_string(nt, e)),
        ir::TypeDef::EnumInt(e) => Some(render_enum_int(nt, e)),
        ir::TypeDef::Union(u) => Some(render_union(spec, nt, u)),
        // Bare Null: skip the canonical singleton (no top-level emit). A
        // user-named Null alias (e.g. `components.schemas.Foo: {type:
        // "null"}`) emits as `type Foo = null;`.
        ir::TypeDef::Null => {
            if nt.id == ir::NULL_ID {
                None
            } else {
                let name = named_ref(nt);
                let mut s = String::new();
                if let Some(d) = &nt.description {
                    s.push_str(&jsdoc(d, ""));
                }
                s.push_str(&format!("export type {name} = null;\n"));
                Some(s)
            }
        }
    }
}

fn render_object(spec: &ir::Ir, nt: &ir::NamedType, obj: &ir::ObjectType) -> String {
    let name = named_ref(nt);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    s.push_str(&format!("export interface {name} {{\n"));
    for prop in &obj.properties {
        let optional = !prop.required;
        let ts_type = render_type_ref(spec, &prop.r#type, None);
        if let Some(d) = &prop.description {
            s.push_str(&jsdoc(d, "  "));
        }
        if is_int64_named(spec, &prop.r#type) {
            s.push_str("  /** int64 in spec — JavaScript `number` loses precision past 2^53. */\n");
        }
        let key = ts_property_key(&prop.name);
        let q = if optional { "?" } else { "" };
        s.push_str(&format!("  {key}{q}: {ts_type};\n"));
    }
    match &obj.additional_properties {
        ir::AdditionalProperties::Any => {
            s.push_str("  [key: string]: unknown;\n");
        }
        ir::AdditionalProperties::Typed { r#type } => {
            let ts = render_type_ref(spec, r#type, None);
            s.push_str(&format!("  [key: string]: {ts};\n"));
        }
        ir::AdditionalProperties::Forbidden => {}
    }
    s.push_str("}\n");
    s
}

fn render_array_alias(spec: &ir::Ir, nt: &ir::NamedType, a: &ir::ArrayType) -> String {
    let name = named_ref(nt);
    let item = render_type_ref(spec, &a.items, None);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    s.push_str(&format!("export type {name} = Array<{item}>;\n"));
    s
}

fn render_map_alias(spec: &ir::Ir, nt: &ir::NamedType, values: &ir::TypeRef) -> String {
    let name = named_ref(nt);
    let v = render_type_ref(spec, values, None);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    s.push_str(&format!("export type {name} = {{ [key: string]: {v} }};\n"));
    s
}

/// "Is this object the canonical map shape?" — empty `properties`
/// (declared fields) plus `additional_properties: Typed { … }`. Returns
/// the values type-ref when true. Issue #109 collapsed `MapType` into
/// this Object spelling.
fn as_map(o: &ir::ObjectType) -> Option<&ir::TypeRef> {
    if !o.properties.is_empty() {
        return None;
    }
    if let ir::AdditionalProperties::Typed { r#type } = &o.additional_properties {
        Some(r#type)
    } else {
        None
    }
}

fn render_enum_string(nt: &ir::NamedType, e: &ir::EnumStringType) -> String {
    let name = named_ref(nt);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    let parts: Vec<String> = e
        .values
        .iter()
        .map(|v| format!("\"{}\"", escape_string_literal(&v.value)))
        .collect();
    let mut body = parts.join(" | ");
    if body.is_empty() {
        body = "never".into();
    }
    s.push_str(&format!("export type {name} = {body};\n"));
    s
}

fn render_enum_int(nt: &ir::NamedType, e: &ir::EnumIntType) -> String {
    let name = named_ref(nt);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    let parts: Vec<String> = e.values.iter().map(|v| v.value.to_string()).collect();
    let mut body = parts.join(" | ");
    if body.is_empty() {
        body = "never".into();
    }
    s.push_str(&format!("export type {name} = {body};\n"));
    s
}

fn render_union(spec: &ir::Ir, nt: &ir::NamedType, u: &ir::UnionType) -> String {
    let name = named_ref(nt);
    let mut s = String::new();
    if let Some(d) = &nt.description {
        s.push_str(&jsdoc(d, ""));
    }
    // Variants pointing at the Null singleton render as the literal `null`
    // via [`render_type_ref`], so multi-variant union-with-Null shapes
    // produce e.g. `string | number | null` automatically. Issue #107.
    let body = match &u.discriminator {
        Some(d) => render_discriminated_body(spec, &d.property_name, &u.variants),
        None => render_plain_union_body(spec, &u.variants),
    };
    let body = if body.is_empty() {
        "never".into()
    } else {
        body
    };
    s.push_str(&format!("export type {name} = {body};\n"));
    s
}

fn render_discriminated_body(
    spec: &ir::Ir,
    property: &str,
    variants: &[ir::UnionVariant],
) -> String {
    let key = ts_property_key(property);
    let parts: Vec<String> = variants
        .iter()
        .map(|v| {
            let ts_type = render_type_ref(spec, &v.r#type, None);
            match &v.tag {
                Some(tag) => format!(
                    "({{ {key}: \"{}\" }} & {ts_type})",
                    escape_string_literal(tag)
                ),
                None => ts_type,
            }
        })
        .collect();
    parts.join(" | ")
}

fn render_plain_union_body(spec: &ir::Ir, variants: &[ir::UnionVariant]) -> String {
    let parts: Vec<String> = variants
        .iter()
        .map(|v| render_type_ref(spec, &v.r#type, None))
        .collect();
    parts.join(" | ")
}

fn ts_property_key(name: &str) -> String {
    if is_safe_property(name) {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

fn is_safe_property(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap();
    if !(first.is_ascii_alphabetic() || first == '_' || first == '$') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn jsdoc(text: &str, indent: &str) -> String {
    let mut s = String::new();
    s.push_str(indent);
    s.push_str("/**\n");
    for line in text.lines() {
        s.push_str(indent);
        s.push_str(" * ");
        s.push_str(line);
        s.push('\n');
    }
    s.push_str(indent);
    s.push_str(" */\n");
    s
}

fn escape_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

fn is_int64_named(spec: &ir::Ir, type_ref: &ir::TypeRef) -> bool {
    // Per #105: int64 signal is `Integer` + `format_extension: int64`.
    spec.types
        .iter()
        .find(|nt| nt.id == *type_ref)
        .map(|nt| match &nt.definition {
            ir::TypeDef::Primitive(p) => {
                matches!(p.kind, ir::PrimitiveKind::Integer)
                    && p.constraints.format_extension.as_deref() == Some("int64")
            }
            _ => false,
        })
        .unwrap_or(false)
}
