// Render README.md for the generated CLI project.

import type { Ir } from '../types.js';

export function renderReadme(ir: Ir, binName: string, envPrefix: string, oauthEnabled: boolean): string {
  const subcommands = ir.operations.map((op) => `\`${kebab(op.id)}\``).join(', ');
  const oauthSection = oauthEnabled
    ? `## OAuth login

The spec declares an oauth2 \`authorizationCode\` flow. Run it once with:

\`\`\`sh
${binName} login
\`\`\`

This opens your browser for the OAuth provider, captures the redirect on
\`http://127.0.0.1:4747/callback\`, exchanges the code for an access token
(PKCE S256), and persists it at the platform's standard config dir
(\`$XDG_CONFIG_HOME/${binName}/auth.json\` on Linux,
\`~/Library/Application Support/${binName}/auth.json\` on macOS,
\`%APPDATA%/${binName}/auth.json\` on Windows; mode \`0600\` on POSIX).

Subsequent invocations pick up the stored token automatically. Refresh
is eager with a 60-second skew. \`${binName} logout\` removes the file.

`
    : '';

  return `# ${ir.info.title} CLI

${ir.info.description ?? ''}

Generated by openapi-forge.

## Install

\`\`\`sh
npm install
npm run build
\`\`\`

## Run

\`\`\`sh
${binName} --help
${binName} <subcommand> --help
\`\`\`

## Auth

Auth resolves in this order: \`--token\` flag → env var → ${oauthEnabled ? 'stored OAuth token (`login` subcommand) → ' : ''}per-scheme env-var fallbacks.

| Env var | Flag | Scheme |
|---|---|---|
| \`${envPrefix}_TOKEN\` | \`--token\` | HTTP bearer |
| \`${envPrefix}_API_KEY\` | \`--api-key\` | API key (header / query / cookie per spec) |
| \`${envPrefix}_USERNAME\`, \`${envPrefix}_PASSWORD\` | \`-u user:pass\` | HTTP basic |

${oauthSection}## Subcommands

${subcommands || '_(none)_'}

## Output

JSON (pretty) by default. \`--output compact\` for one-line, \`--output table\`
for a simple ASCII table when the response is an array of objects.

## Errors

Non-2xx responses are printed to stderr with their body and the process
exits with a status code derived from the HTTP status (capped at 255).
`;
}

function kebab(s: string): string {
  return s.replace(/[A-Z]+/g, (m, idx: number) => (idx === 0 ? m.toLowerCase() : '-' + m.toLowerCase()));
}
