// Static text included verbatim in the generated CLI project. Same shape
// as generator-typescript-fetch's runtime; the query-string helpers are
// the canonical implementation of OpenAPI parameter `style`+`explode`
// rules and are copied with one minor change (use `globalThis.fetch` so
// Node ≥18 picks up the built-in fetch without an extra import).

export const RUNTIME_TS = `// Generated by openapi-forge — do not edit by hand.

export interface RequestOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

/** Permissive union for OAS \`format: byte\` (base64 string) and
 *  \`format: binary\` (raw bytes). */
export type BinaryData = string | Blob | ArrayBuffer | Uint8Array;

export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(status: number, body: unknown, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }

  static async fromResponse(res: Response): Promise<ApiError> {
    let body: unknown = null;
    try {
      body = await res.json();
    } catch {
      try {
        body = await res.text();
      } catch {
        body = null;
      }
    }
    return new ApiError(res.status, body, \`HTTP \${res.status} \${res.statusText}\`);
  }
}

export const JSON_HEADERS: Record<string, string> = { "content-type": "application/json" };

export function joinUrl(baseUrl: string, path: string): string {
  if (baseUrl.length === 0) return path;
  if (baseUrl.endsWith("/") && path.startsWith("/")) return baseUrl + path.slice(1);
  if (!baseUrl.endsWith("/") && !path.startsWith("/")) return baseUrl + "/" + path;
  return baseUrl + path;
}

/** \`style: form\`. \`explode: true\` repeats the key per array item; otherwise comma-joins. */
export function appendQueryForm(
  url: string,
  key: string,
  value: unknown,
  explode: boolean,
): string {
  if (value === undefined || value === null) return url;
  if (Array.isArray(value)) {
    if (value.length === 0) return url;
    if (explode) {
      const parts = value.map(
        (v) => \`\${encodeURIComponent(key)}=\${encodeURIComponent(String(v))}\`,
      );
      return appendRaw(url, parts.join("&"));
    }
    const joined = value.map((v) => encodeURIComponent(String(v))).join(",");
    return appendRaw(url, \`\${encodeURIComponent(key)}=\${joined}\`);
  }
  return appendRaw(
    url,
    \`\${encodeURIComponent(key)}=\${encodeURIComponent(String(value))}\`,
  );
}

/** \`style: pipeDelimited\` / \`spaceDelimited\`. */
export function appendQueryDelimited(
  url: string,
  key: string,
  values: readonly unknown[] | null | undefined,
  delimiter: string,
): string {
  if (!values || values.length === 0) return url;
  const joined = values.map((v) => encodeURIComponent(String(v))).join(delimiter);
  return appendRaw(url, \`\${encodeURIComponent(key)}=\${joined}\`);
}

/** \`style: deepObject\`: \`?k[a]=1&k[b]=2\`. */
export function appendQueryDeepObject(
  url: string,
  key: string,
  value: Record<string, unknown> | null | undefined,
): string {
  if (!value) return url;
  let out = url;
  for (const [k, v] of Object.entries(value)) {
    if (v === undefined || v === null) continue;
    out = appendRaw(
      out,
      \`\${encodeURIComponent(\`\${key}[\${k}]\`)}=\${encodeURIComponent(String(v))}\`,
    );
  }
  return out;
}

function appendRaw(url: string, suffix: string): string {
  const sep = url.includes("?") ? "&" : "?";
  return url + sep + suffix;
}
`;

export const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2022"],
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*.ts"]
}
`;

export const FORMAT_TS = `// Output formatting: pretty JSON by default; --compact one-line; --output table
// renders an array-of-object as a simple ASCII table (best-effort).

export type OutputMode = "json" | "compact" | "table";

export function formatOutput(value: unknown, mode: OutputMode): string {
  if (mode === "compact") return JSON.stringify(value);
  if (mode === "table" && Array.isArray(value) && value.length > 0 && typeof value[0] === "object" && value[0] !== null) {
    return renderTable(value as Record<string, unknown>[]);
  }
  return JSON.stringify(value, null, 2);
}

function renderTable(rows: Record<string, unknown>[]): string {
  const cols = Array.from(new Set(rows.flatMap((r) => Object.keys(r))));
  const cells = rows.map((r) => cols.map((c) => stringify(r[c])));
  const widths = cols.map((c, i) =>
    Math.max(c.length, ...cells.map((row) => row[i]!.length)),
  );
  const sep = widths.map((w) => "-".repeat(w)).join("  ");
  const header = cols.map((c, i) => c.padEnd(widths[i]!)).join("  ");
  const body = cells.map((row) => row.map((v, i) => v.padEnd(widths[i]!)).join("  "));
  return [header, sep, ...body].join("\\n");
}

function stringify(v: unknown): string {
  if (v === null || v === undefined) return "";
  if (typeof v === "object") return JSON.stringify(v);
  return String(v);
}
`;
