package emit

import (
	"fmt"
	"strings"
)

// Server renders the contents of `server.go`: a `Server` interface with one
// method per operation, plus `RegisterRoutes` that wires `*http.ServeMux`
// pattern strings (Go 1.22+) to a stub that decodes path params and calls
// the user-supplied implementation.
//
// Body decoding is deliberately out of scope: handlers receive
// `*http.Request` and write to `http.ResponseWriter` themselves. Path
// params are decoded and passed as typed arguments.
func Server(packageName string, spec Spec) string {
	var b strings.Builder
	b.WriteString("// Code generated by generator-go-server. DO NOT EDIT.\n")
	b.WriteString("// Source: ")
	b.WriteString(spec.Title)
	if spec.Version != "" {
		b.WriteString(" v")
		b.WriteString(spec.Version)
	}
	b.WriteString("\n\n")

	fmt.Fprintf(&b, "package %s\n\n", packageName)

	b.WriteString(`import (
	"net/http"
	"strconv"
)

`)

	// Server interface
	if spec.Description != "" {
		writeDocComment(&b, spec.Description)
	} else {
		fmt.Fprintf(&b, "// Server is the application interface for %s.\n", spec.Title)
	}
	b.WriteString("// Implementations decode request bodies and write responses themselves.\n")
	b.WriteString("type Server interface {\n")
	for _, op := range spec.Operations {
		if op.Doc != "" {
			b.WriteString("\t")
			writeDocCommentInline(&b, op.Doc)
		}
		fmt.Fprintf(&b, "\t%s%s\n", op.ID, methodSignature(op))
	}
	b.WriteString("}\n\n")

	// Route registration
	b.WriteString(`// RegisterRoutes wires every operation onto mux using Go 1.22+ pattern
// syntax ("METHOD /path/{param}"). Path parameters are decoded into typed
// values before dispatch; type-conversion failures return 400.
func RegisterRoutes(mux *http.ServeMux, srv Server) {
`)
	for _, op := range spec.Operations {
		pattern := fmt.Sprintf("%s %s", op.Method, op.Path)
		fmt.Fprintf(&b, "\tmux.HandleFunc(%q, func(w http.ResponseWriter, r *http.Request) {\n", pattern)
		writeHandlerBody(&b, op)
		b.WriteString("\t})\n")
	}
	b.WriteString("}\n\n")

	// Decode helpers
	b.WriteString(decodeHelpers)

	return b.String()
}

func methodSignature(op Operation) string {
	var b strings.Builder
	b.WriteString("(w http.ResponseWriter, r *http.Request")
	for _, p := range op.PathParams {
		fmt.Fprintf(&b, ", %s %s", p.Name, p.GoType)
	}
	b.WriteString(")")
	return b.String()
}

func writeHandlerBody(b *strings.Builder, op Operation) {
	for _, p := range op.PathParams {
		switch p.GoType {
		case "string":
			fmt.Fprintf(b, "\t\t%s := r.PathValue(%q)\n", p.Name, originalParamName(op, p))
		case "int32":
			fmt.Fprintf(b, "\t\t%s, err := decodeInt32(r, %q)\n", p.Name, originalParamName(op, p))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n")
			b.WriteString("\t\t\treturn\n")
			b.WriteString("\t\t}\n")
		case "int64":
			fmt.Fprintf(b, "\t\t%s, err := decodeInt64(r, %q)\n", p.Name, originalParamName(op, p))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n")
			b.WriteString("\t\t\treturn\n")
			b.WriteString("\t\t}\n")
		case "float64":
			fmt.Fprintf(b, "\t\t%s, err := decodeFloat64(r, %q)\n", p.Name, originalParamName(op, p))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n")
			b.WriteString("\t\t\treturn\n")
			b.WriteString("\t\t}\n")
		case "bool":
			fmt.Fprintf(b, "\t\t%s, err := decodeBool(r, %q)\n", p.Name, originalParamName(op, p))
			b.WriteString("\t\tif err != nil {\n")
			b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n")
			b.WriteString("\t\t\treturn\n")
			b.WriteString("\t\t}\n")
		default:
			// Fallback: pass through as string.
			fmt.Fprintf(b, "\t\t%s := r.PathValue(%q)\n", p.Name, originalParamName(op, p))
		}
	}
	fmt.Fprintf(b, "\t\tsrv.%s(w, r", op.ID)
	for _, p := range op.PathParams {
		fmt.Fprintf(b, ", %s", p.Name)
	}
	b.WriteString(")\n")
}

// originalParamName is the {placeholder} key the path-template uses. The Go
// http.ServeMux exposes path values by that key — not by the sanitized
// Go identifier — so we have to remember the raw OpenAPI name.
//
// We stash the original on Parameter.Name (the lowerCamel sanitized form
// equals the OpenAPI name in most cases). For now derive from the path
// template by parsing.
func originalParamName(op Operation, p Parameter) string {
	// Path templates look like /pets/{petId}. The PathValue key matches
	// what's in braces, which is the *original* name. The renderer stashes
	// it via the same lowerCamel transformation, so this is the simplest
	// correct fallback: search the template for a brace whose lowerCamel
	// projection matches.
	raw := op.Path
	for {
		open := strings.IndexByte(raw, '{')
		if open < 0 {
			break
		}
		close := strings.IndexByte(raw[open:], '}')
		if close < 0 {
			break
		}
		name := raw[open+1 : open+close]
		if LowerCamel(name) == p.Name {
			return name
		}
		raw = raw[open+close+1:]
	}
	return p.Name
}

func writeDocComment(b *strings.Builder, doc string) {
	for _, line := range strings.Split(strings.TrimSpace(doc), "\n") {
		fmt.Fprintf(b, "// %s\n", line)
	}
}

func writeDocCommentInline(b *strings.Builder, doc string) {
	lines := strings.Split(strings.TrimSpace(doc), "\n")
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "// %s\n", lines[0])
	for _, line := range lines[1:] {
		fmt.Fprintf(b, "\t// %s\n", line)
	}
}

const decodeHelpers = `func decodeInt32(r *http.Request, key string) (int32, error) {
	v, err := strconv.ParseInt(r.PathValue(key), 10, 32)
	if err != nil {
		return 0, err
	}
	return int32(v), nil
}

func decodeInt64(r *http.Request, key string) (int64, error) {
	return strconv.ParseInt(r.PathValue(key), 10, 64)
}

func decodeFloat64(r *http.Request, key string) (float64, error) {
	return strconv.ParseFloat(r.PathValue(key), 64)
}

func decodeBool(r *http.Request, key string) (bool, error) {
	return strconv.ParseBool(r.PathValue(key))
}
`
