//! Orchestrate file emission: 6 [`OutputFile`]s per spec.

use forge_plugin_sdk::ir;
use forge_plugin_sdk::{GenerationOutput, OutputFile};

use crate::bodies::spec_uses_multipart;
use crate::operations::render_client_module;
use crate::types::render_models_module;

#[derive(Debug, Clone)]
pub struct Config {
    pub crate_name: String,
    pub base_url: Option<String>,
}

// Static templates kept outside `src/` (`.in` extension) so rustc doesn't
// try to compile them as part of the plugin.
const ERROR_RS: &str = include_str!("../templates/error.rs.in");
const LIB_RS: &str = include_str!("../templates/lib.rs.in");

pub fn all(spec: &ir::Ir, cfg: &Config) -> GenerationOutput {
    let base_url = cfg
        .base_url
        .clone()
        .or_else(|| spec.servers.first().map(|s| s.url.clone()))
        .unwrap_or_default();

    let cargo_toml = render_cargo_toml(&cfg.crate_name, &spec.info, spec);
    let readme = render_readme(&cfg.crate_name, &spec.info);
    let lib_rs = LIB_RS.to_string();
    let models_rs = render_models_module(spec);
    let client_rs = render_client_module(spec, &base_url);
    let error_rs = ERROR_RS.to_string();

    let files = vec![
        OutputFile {
            path: "Cargo.toml".into(),
            content: cargo_toml.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
        OutputFile {
            path: "README.md".into(),
            content: readme.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
        OutputFile {
            path: "src/lib.rs".into(),
            content: lib_rs.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
        OutputFile {
            path: "src/models.rs".into(),
            content: models_rs.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
        OutputFile {
            path: "src/client.rs".into(),
            content: client_rs.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
        OutputFile {
            path: "src/error.rs".into(),
            content: error_rs.into_bytes(),
            mode: forge_plugin_sdk::FileMode::Text,
        },
    ];

    GenerationOutput {
        files,
        diagnostics: vec![],
    }
}

fn render_cargo_toml(crate_name: &str, info: &ir::ApiInfo, spec: &ir::Ir) -> String {
    // We deliberately pin minor versions and disable default features for
    // reqwest so the consumer gets rustls-only TLS without dragging in
    // `native-tls` / OpenSSL.
    let mut s = String::new();
    s.push_str("# Generated by openapi-forge — do not edit by hand.\n");
    let version_for_cargo = match coerce_semver(&info.version) {
        Some(v) => v,
        None => {
            s.push_str(&format!(
                "# original API version: {}\n",
                escape_for_comment(&info.version)
            ));
            "0.0.0".to_string()
        }
    };
    s.push('\n');
    s.push_str("[package]\n");
    s.push_str(&format!("name = \"{}\"\n", escape_toml(crate_name)));
    s.push_str(&format!("version = \"{}\"\n", escape_toml(&version_for_cargo)));
    s.push_str("edition = \"2021\"\n");
    s.push_str(&format!(
        "description = \"Generated client for {}.\"\n",
        escape_toml(&info.title)
    ));
    s.push_str("\n[dependencies]\n");

    // Conditionally enable the `multipart` feature only if the spec
    // actually uses it — keeps the dep-graph smaller for specs that
    // don't.
    let mut reqwest_features = vec!["\"rustls-tls\"", "\"json\""];
    if spec_uses_multipart(spec) {
        reqwest_features.push("\"multipart\"");
    }
    s.push_str(&format!(
        "reqwest = {{ version = \"0.12\", default-features = false, features = [{}] }}\n",
        reqwest_features.join(", ")
    ));
    s.push_str("serde = { version = \"1.0\", features = [\"derive\"] }\n");
    s.push_str("serde_json = \"1.0\"\n");
    // Used by the inline URL helpers in `client.rs` (path / query /
    // cookie percent-encoding). ~5 KB, no transitive deps.
    s.push_str("percent-encoding = \"2\"\n");
    s.push_str("thiserror = \"2.0\"\n");
    s
}

fn render_readme(crate_name: &str, info: &ir::ApiInfo) -> String {
    let mut s = String::new();
    s.push_str(&format!("# {}\n\n", info.title));
    if let Some(desc) = &info.description {
        s.push_str(desc);
        s.push_str("\n\n");
    }
    s.push_str(&format!(
        "Generated by [openapi-forge](https://github.com/marcusdunn/openapi-forge) — version {}.\n\n",
        info.version
    ));
    s.push_str("## Usage\n\n");
    s.push_str("```rust,no_run\n");
    s.push_str(&format!("use {}::ApiClient;\n", crate_name.replace('-', "_")));
    s.push('\n');
    s.push_str("# async fn run() -> Result<(), Box<dyn std::error::Error>> {\n");
    s.push_str("let client = ApiClient::new(None);\n");
    s.push_str("// call methods on `client`...\n");
    s.push_str("# Ok(()) }\n");
    s.push_str("```\n\n");
    s.push_str(
        "Bring your own async runtime (`tokio`, `async-std`, …); this crate does not pull one in.\n",
    );
    s
}

/// Hand-rolled SemVer 2.0 validator. Returns `Some(raw.to_string())` if
/// `raw` already parses as a SemVer, `None` otherwise. We don't pull the
/// `semver` crate in just for this — a plugin-author dep added once
/// shows up in every plugin's WASM image.
///
/// Spec: <https://semver.org/spec/v2.0.0.html>.
fn coerce_semver(raw: &str) -> Option<String> {
    // Split off optional build metadata (`+...`).
    let (after_build_split, _build) = match raw.split_once('+') {
        Some((before, build)) => (before, Some(build)),
        None => (raw, None),
    };
    if let Some(b) = _build {
        if !is_valid_dot_separated_idents(b, /*allow_leading_zero=*/ true) {
            return None;
        }
    }

    // Split off optional pre-release (`-...`). Only the *first* `-` after
    // the major.minor.patch core counts.
    let (core, pre) = match after_build_split.split_once('-') {
        Some((c, p)) => (c, Some(p)),
        None => (after_build_split, None),
    };
    if let Some(p) = pre {
        if !is_valid_dot_separated_idents(p, /*allow_leading_zero=*/ false) {
            return None;
        }
    }

    // Core must be exactly major.minor.patch.
    let parts: Vec<&str> = core.split('.').collect();
    if parts.len() != 3 {
        return None;
    }
    for p in &parts {
        if !is_valid_numeric_ident(p) {
            return None;
        }
    }
    Some(raw.to_string())
}

fn is_valid_numeric_ident(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    if s.len() > 1 && s.starts_with('0') {
        return false;
    }
    s.chars().all(|c| c.is_ascii_digit())
}

fn is_valid_dot_separated_idents(s: &str, allow_leading_zero: bool) -> bool {
    if s.is_empty() {
        return false;
    }
    s.split('.').all(|ident| {
        if ident.is_empty() {
            return false;
        }
        let all_digits = ident.chars().all(|c| c.is_ascii_digit());
        if all_digits {
            return allow_leading_zero || is_valid_numeric_ident(ident);
        }
        ident
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-')
    })
}

/// Strip control characters and replace newlines so a raw string is safe
/// to drop into a TOML `# ...` comment without breaking the file.
fn escape_for_comment(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\n' | '\r' => out.push(' '),
            c if c.is_control() => {} // drop
            c => out.push(c),
        }
    }
    out
}

fn escape_toml(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c => out.push(c),
        }
    }
    out
}
