//! IR `Operation` → Rust async-method source for `client.rs`.
//!
//! Orchestration only. Body picking and rendering live in `bodies.rs`;
//! path / query / header / cookie params live in `params.rs`.

use forge_plugin_sdk::ir;

use crate::bodies::{body_signature, pick_body, render_body_assembly, BodyPick};
use crate::naming::rust_ident_snake;
use crate::params::{
    render_cookie_assembly, render_header_assembly, render_query_assembly,
    render_url_construction, URL_HELPERS,
};
use crate::types::render_type_ref;
use crate::util::string_literal;

/// Render the entire `client.rs` source.
pub fn render_client_module(spec: &ir::Ir, default_base_url: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    s.push_str("#![allow(unused_variables, unused_mut, dead_code)]\n\n");
    s.push_str("use crate::error::ApiError;\n");
    s.push_str("#[allow(unused_imports)]\n");
    s.push_str("use crate::models::*;\n\n");

    s.push_str(URL_HELPERS);

    let has_auth = !spec.security_schemes.is_empty();
    if has_auth {
        s.push_str(&render_auth_config(spec));
    }

    s.push_str("/// Async client for the API.\n");
    s.push_str("#[derive(Debug, Clone)]\n");
    s.push_str("pub struct ApiClient {\n");
    s.push_str("    base_url: String,\n");
    s.push_str("    http: reqwest::Client,\n");
    if has_auth {
        s.push_str("    auth: Option<AuthConfig>,\n");
    }
    s.push_str("}\n\n");

    s.push_str("impl ApiClient {\n");
    s.push_str(&format!(
        "    /// Construct a client. Pass `None` to use the spec-default base URL ({default_base_url:?}).\n"
    ));
    if has_auth {
        s.push_str("    pub fn new(base_url: Option<String>, auth: Option<AuthConfig>) -> Self {\n");
        s.push_str(&format!(
            "        let base_url = base_url.unwrap_or_else(|| {}.to_string());\n",
            string_literal(default_base_url),
        ));
        s.push_str("        Self {\n");
        s.push_str("            base_url,\n");
        s.push_str("            http: reqwest::Client::new(),\n");
        s.push_str("            auth,\n");
        s.push_str("        }\n");
        s.push_str("    }\n\n");
    } else {
        s.push_str("    pub fn new(base_url: Option<String>) -> Self {\n");
        s.push_str(&format!(
            "        let base_url = base_url.unwrap_or_else(|| {}.to_string());\n",
            string_literal(default_base_url),
        ));
        s.push_str("        Self {\n");
        s.push_str("            base_url,\n");
        s.push_str("            http: reqwest::Client::new(),\n");
        s.push_str("        }\n");
        s.push_str("    }\n\n");
    }

    s.push_str("    /// Construct a client from an existing `reqwest::Client`.\n");
    if has_auth {
        s.push_str(
            "    pub fn with_client(base_url: String, http: reqwest::Client, auth: Option<AuthConfig>) -> Self {\n",
        );
        s.push_str("        Self { base_url, http, auth }\n");
    } else {
        s.push_str("    pub fn with_client(base_url: String, http: reqwest::Client) -> Self {\n");
        s.push_str("        Self { base_url, http }\n");
    }
    s.push_str("    }\n\n");

    for op in &spec.operations {
        s.push_str(&render_operation(spec, op, has_auth));
        s.push('\n');
    }
    s.push_str("}\n");
    s
}

fn render_auth_config(spec: &ir::Ir) -> String {
    let mut variants: Vec<&str> = Vec::new();
    for scheme in &spec.security_schemes {
        match &scheme.kind {
            ir::SecuritySchemeKind::ApiKey(_) => {
                if !variants.contains(&"ApiKey") {
                    variants.push("ApiKey");
                }
            }
            ir::SecuritySchemeKind::HttpBearer { .. } => {
                if !variants.contains(&"Bearer") {
                    variants.push("Bearer");
                }
            }
            ir::SecuritySchemeKind::HttpBasic => {
                if !variants.contains(&"Basic") {
                    variants.push("Basic");
                }
            }
            // oauth2 / openIdConnect / mutualTLS: no AuthConfig variant.
            // oauth2 + openIdConnect run externally; mTLS is configured
            // on the underlying reqwest::Client (identity / native-tls /
            // rustls). Bearer flows still use the Bearer arm.
            ir::SecuritySchemeKind::Oauth2(_)
            | ir::SecuritySchemeKind::OpenIdConnect { .. }
            | ir::SecuritySchemeKind::MutualTls => {}
        }
    }
    if variants.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("/// How the client authenticates each request.\n");
    s.push_str("#[derive(Debug, Clone)]\n");
    s.push_str("pub enum AuthConfig {\n");
    if variants.contains(&"ApiKey") {
        s.push_str("    ApiKey { key: String },\n");
    }
    if variants.contains(&"Bearer") {
        s.push_str("    Bearer { token: String },\n");
    }
    if variants.contains(&"Basic") {
        s.push_str("    Basic { username: String, password: String },\n");
    }
    s.push_str("}\n\n");
    s
}

#[derive(Debug, Clone)]
enum ResponsePick<'a> {
    Unit,
    Json(&'a ir::TypeRef),
}

fn pick_response(op: &ir::Operation) -> ResponsePick<'_> {
    for r in &op.responses {
        let two_xx = match &r.status {
            ir::ResponseStatus::Explicit { code } => (200..300).contains(code),
            ir::ResponseStatus::Range { class } => *class == 2,
            ir::ResponseStatus::Default => false,
        };
        if !two_xx {
            continue;
        }
        if let Some(json) = r
            .content
            .iter()
            .find(|c| c.media_type.starts_with("application/json"))
        {
            return ResponsePick::Json(&json.r#type);
        }
    }
    ResponsePick::Unit
}

/// Render a method as a reqwest `Method` constructor expression.
/// Standard verbs use the named associated constants
/// (`reqwest::Method::GET`); 3.2 `additionalOperations` (e.g.
/// `QUERY`) use `Method::from_bytes(b"QUERY").unwrap()` since reqwest
/// has no constant for them.
fn http_method_expr(m: &ir::HttpMethod) -> String {
    match m {
        ir::HttpMethod::Get => "reqwest::Method::GET".to_string(),
        ir::HttpMethod::Put => "reqwest::Method::PUT".to_string(),
        ir::HttpMethod::Post => "reqwest::Method::POST".to_string(),
        ir::HttpMethod::Delete => "reqwest::Method::DELETE".to_string(),
        ir::HttpMethod::Options => "reqwest::Method::OPTIONS".to_string(),
        ir::HttpMethod::Head => "reqwest::Method::HEAD".to_string(),
        ir::HttpMethod::Patch => "reqwest::Method::PATCH".to_string(),
        ir::HttpMethod::Trace => "reqwest::Method::TRACE".to_string(),
        ir::HttpMethod::Other(s) => {
            // The verb is upper-cased in the IR; pass the bytes
            // through to reqwest's parser. `unwrap` is safe because
            // the parser already validated method-name shape.
            format!("reqwest::Method::from_bytes(b\"{s}\").unwrap()")
        }
    }
}

fn render_operation(spec: &ir::Ir, op: &ir::Operation, has_auth: bool) -> String {
    let method_name = rust_ident_snake(&op.id);
    let body_pick = pick_body(op);
    let resp_pick = pick_response(op);

    // Signature.
    let mut sig = String::new();
    if let Some(doc) = &op.documentation {
        for line in doc.lines() {
            sig.push_str("    /// ");
            sig.push_str(line);
            sig.push('\n');
        }
    }
    sig.push_str("    pub async fn ");
    sig.push_str(&method_name);
    sig.push_str("(&self");

    let mut sig_params: Vec<String> = Vec::new();
    for p in &op.path_params {
        let name = rust_ident_snake(&p.name);
        let ty = render_type_ref(spec, &p.r#type);
        sig_params.push(format!("{name}: {ty}"));
    }
    for p in &op.query_params {
        let name = rust_ident_snake(&p.name);
        let mut ty = render_type_ref(spec, &p.r#type);
        if !p.required && !ty.starts_with("Option<") {
            ty = format!("Option<{ty}>");
        }
        sig_params.push(format!("{name}: {ty}"));
    }
    for p in &op.header_params {
        let name = rust_ident_snake(&p.name);
        let mut ty = render_type_ref(spec, &p.r#type);
        if !p.required && !ty.starts_with("Option<") {
            ty = format!("Option<{ty}>");
        }
        sig_params.push(format!("{name}: {ty}"));
    }
    for p in &op.cookie_params {
        let name = rust_ident_snake(&p.name);
        let mut ty = render_type_ref(spec, &p.r#type);
        if !p.required && !ty.starts_with("Option<") {
            ty = format!("Option<{ty}>");
        }
        sig_params.push(format!("{name}: {ty}"));
    }
    if let Some((n, t)) = body_signature(spec, &body_pick) {
        sig_params.push(format!("{n}: {t}"));
    }
    for p in sig_params {
        sig.push_str(", ");
        sig.push_str(&p);
    }
    sig.push_str(") -> Result<");
    match &resp_pick {
        ResponsePick::Unit => sig.push_str("()"),
        ResponsePick::Json(ty) => sig.push_str(&render_type_ref(spec, ty)),
    }
    sig.push_str(", ApiError> {\n");

    // Body.
    let mut body = String::new();
    body.push_str(&render_url_construction(spec, op));
    body.push_str(&render_query_assembly(spec, op));
    body.push_str(&format!(
        "        let mut req = self.http.request({}, &url);\n",
        http_method_expr(&op.method)
    ));
    body.push_str(&render_header_assembly(spec, op));
    body.push_str(&render_cookie_assembly(spec, op));
    if has_auth {
        body.push_str(&render_auth_application(spec));
    }
    body.push_str(&render_body_assembly(spec, &body_pick));
    body.push_str("        let res = req.send().await.map_err(ApiError::from)?;\n");
    body.push_str("        let status = res.status();\n");
    body.push_str("        if !status.is_success() {\n");
    body.push_str("            let body = res.json::<serde_json::Value>().await.ok();\n");
    body.push_str("            return Err(ApiError::Status { code: status.as_u16(), body });\n");
    body.push_str("        }\n");
    match &resp_pick {
        ResponsePick::Unit => {
            body.push_str("        Ok(())\n");
        }
        ResponsePick::Json(_) => {
            body.push_str("        let parsed = res.json().await.map_err(ApiError::from)?;\n");
            body.push_str("        Ok(parsed)\n");
        }
    }
    body.push_str("    }\n");

    sig + &body
}

fn render_auth_application(spec: &ir::Ir) -> String {
    let mut arms = String::new();
    let mut handled: Vec<&'static str> = Vec::new();
    for scheme in &spec.security_schemes {
        match &scheme.kind {
            ir::SecuritySchemeKind::ApiKey(api) if !handled.contains(&"ApiKey") => {
                handled.push("ApiKey");
                let header_name = match api.location {
                    ir::ApiKeyLocation::Header => string_literal(&api.name),
                    _ => string_literal(&api.name),
                };
                arms.push_str(&format!(
                    "                AuthConfig::ApiKey {{ key }} => {{ req = req.header({header_name}, key); }}\n"
                ));
            }
            ir::SecuritySchemeKind::HttpBearer { .. } if !handled.contains(&"Bearer") => {
                handled.push("Bearer");
                arms.push_str(
                    "                AuthConfig::Bearer { token } => { req = req.bearer_auth(token); }\n",
                );
            }
            ir::SecuritySchemeKind::HttpBasic if !handled.contains(&"Basic") => {
                handled.push("Basic");
                arms.push_str(
                    "                AuthConfig::Basic { username, password } => { req = req.basic_auth(username, Some(password)); }\n",
                );
            }
            // oauth2 / openIdConnect / mutualTLS: no auth-application
            // arm. Consumers pass the resulting bearer token via
            // AuthConfig::Bearer; mTLS lives on the reqwest::Client.
            ir::SecuritySchemeKind::Oauth2(_)
            | ir::SecuritySchemeKind::OpenIdConnect { .. }
            | ir::SecuritySchemeKind::MutualTls => {}
            // Already-handled variants that re-appear (e.g. two http-bearer
            // schemes with different bearerFormat hints) — keep the first.
            _ => {}
        }
    }
    if arms.is_empty() {
        return String::new();
    }
    let mut s = String::new();
    s.push_str("        if let Some(auth) = &self.auth {\n");
    s.push_str("            match auth {\n");
    s.push_str(&arms);
    s.push_str("            }\n");
    s.push_str("        }\n");
    s
}

// Suppress dead-code warnings — the symbols are used at
// `cargo build --target wasm32-wasip2` time but appear unused under
// host `cargo check` (which we don't actually run on this crate).
#[allow(dead_code)]
fn _ensure_body_pick_referenced(_b: BodyPick<'_>) {}
