//! IR `TypeDef` → Rust source.
//!
//! Two entry points: [`render_type_ref`] inlines a reference at a use
//! site (`Option<i32>`, `Vec<Pet>`); [`render_models_module`] emits all
//! the named composite types as a complete `models.rs` source file.

use forge_plugin_sdk::ir;
use forge_plugin_sdk::{peel_nullable, union_has_null};

use crate::naming::{rust_ident_pascal, rust_ident_snake};

/// Render a `TypeRef` at a use site. The returned string is a complete
/// Rust type expression (`i32`, `String`, `Option<Vec<Pet>>`, etc.).
pub fn render_type_ref(spec: &ir::Ir, type_ref: &ir::TypeRef) -> String {
    // The canonical `T | null` shape (issue #107) is a two-variant Union
    // whose other arm is the Null singleton. Peel it here so every
    // call-site renders `Option<T>` without each generator branch having
    // to know.
    if let Some(inner) = peel_nullable(&spec.types, type_ref) {
        return format!("Option<{}>", render_type_ref(spec, inner));
    }
    let Some(nt) = spec.types.iter().find(|nt| nt.id == *type_ref) else {
        return "serde_json::Value /* unresolved type-ref */".into();
    };
    match &nt.definition {
        ir::TypeDef::Primitive(p) => primitive_rust(p),
        ir::TypeDef::Array(a) => {
            let inner = render_type_ref(spec, &a.items);
            format!("Vec<{inner}>")
        }
        ir::TypeDef::Object(o) => match as_map(o) {
            Some(values_ref) => {
                let inner = render_type_ref(spec, values_ref);
                format!("std::collections::HashMap<String, {inner}>")
            }
            None => named_ref(nt),
        },
        ir::TypeDef::EnumString(_) | ir::TypeDef::EnumInt(_) => named_ref(nt),
        ir::TypeDef::Union(u) => {
            // A multi-variant union that *contains* Null is rendered as
            // `Option<EnumName>` — the enum body filters the Null variant
            // out (see render_union).
            if union_has_null(&spec.types, u) {
                format!("Option<{}>", named_ref(nt))
            } else {
                named_ref(nt)
            }
        }
        // The bare Null singleton has no in-place Rust spelling; serde
        // round-trips it as `()`. Generators rarely render this directly
        // because nullable wraps go through `peel_nullable` above.
        ir::TypeDef::Null => "()".into(),
    }
}

/// PascalCase reference for a composite type. Prefers `original_name`,
/// falls back to `id`.
pub fn named_ref(nt: &ir::NamedType) -> String {
    let raw = nt.original_name.as_deref().unwrap_or(&nt.id);
    rust_ident_pascal(raw)
}

fn primitive_rust(p: &ir::PrimitiveType) -> String {
    // Per #105 the IR carries the JSON Schema `type` value only; the
    // OAS `format` lands in `format_extension`. Pick richer Rust types
    // when the format hints at a width or a binary encoding;
    // everything else collapses to a sensible default.
    let fmt = p.constraints.format_extension.as_deref();
    match (p.kind, fmt) {
        // Binary encodings → Vec<u8>. serde encodes as a JSON array by
        // default; consumers who want true base64 can wrap with
        // #[serde(with = "serde_bytes")].
        (ir::PrimitiveKind::String, Some("byte" | "binary")) => "Vec<u8>".into(),
        // String-typed formats (date, date-time, uuid, uri, email,
        // password, decimal, etc.) all fold to String for v1.
        // Strongly-typed mappings (chrono::DateTime, uuid::Uuid,
        // rust_decimal::Decimal, …) are a follow-up — each pulls a
        // public dep onto every consumer.
        (ir::PrimitiveKind::String, _) => "String".into(),
        (ir::PrimitiveKind::Integer, Some("int32")) => "i32".into(),
        (ir::PrimitiveKind::Integer, _) => "i64".into(),
        (ir::PrimitiveKind::Number, Some("float")) => "f32".into(),
        (ir::PrimitiveKind::Number, _) => "f64".into(),
        (ir::PrimitiveKind::Bool, _) => "bool".into(),
    }
}

/// Emit `models.rs`: every composite named type as a struct / enum /
/// type alias. Includes the `use` declarations the generated code
/// needs.
pub fn render_models_module(spec: &ir::Ir) -> String {
    let mut out = String::new();
    out.push_str("// Generated by openapi-forge — do not edit by hand.\n\n");
    out.push_str("#![allow(unused_imports, dead_code, clippy::large_enum_variant)]\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");
    let mut emitted = 0usize;
    for nt in &spec.types {
        if let Some(s) = render_named_type(spec, nt) {
            out.push_str(&s);
            out.push('\n');
            emitted += 1;
        }
    }
    if emitted == 0 {
        // Avoid an empty module; emit a no-op.
        out.push_str("// (no named composite types in this spec)\n");
    }
    out
}

/// Render a top-level Rust item. Returns `None` for types that are
/// always inlined (primitives; arrays / maps that are component-level
/// are emitted as type aliases instead).
pub fn render_named_type(spec: &ir::Ir, nt: &ir::NamedType) -> Option<String> {
    // The canonical `T | null` shape is a Union with exactly two variants
    // — emit it as a `pub type X = Option<Inner>;` alias instead of a
    // hand-rolled enum (issue #107).
    if let Some(inner) = peel_nullable(&spec.types, &nt.id) {
        let name = named_ref(nt);
        let inner_ts = render_type_ref(spec, inner);
        let mut s = doc_comment(nt.documentation.as_deref());
        s.push_str(&format!("pub type {name} = Option<{inner_ts}>;\n"));
        return Some(s);
    }
    match &nt.definition {
        ir::TypeDef::Primitive(_) => None,
        ir::TypeDef::Object(o) => {
            // Map shape: empty properties + typed additional
            // properties. Issue #109 collapsed MapType into this
            // canonical Object form; render as a `HashMap` alias.
            if let Some(values_ref) = as_map(o) {
                Some(render_map_alias(spec, nt, values_ref))
            } else {
                Some(render_object(spec, nt, o))
            }
        }
        ir::TypeDef::Array(a) => Some(render_array_alias(spec, nt, a)),
        ir::TypeDef::EnumString(e) => Some(render_enum_string(nt, e)),
        ir::TypeDef::EnumInt(e) => Some(render_enum_int(nt, e)),
        ir::TypeDef::Union(u) => Some(render_union(spec, nt, u)),
        // Null is a marker; the singleton is never emitted as a top-level
        // Rust item. Named Null aliases (e.g. `components.schemas.Foo:
        // {type: "null"}`) produce a `pub type Foo = ();` aliasing.
        ir::TypeDef::Null => {
            if nt.id == ir::NULL_ID {
                None
            } else {
                let name = named_ref(nt);
                let mut s = doc_comment(nt.documentation.as_deref());
                s.push_str(&format!("pub type {name} = ();\n"));
                Some(s)
            }
        }
    }
}

fn doc_comment(doc: Option<&str>) -> String {
    let Some(text) = doc else {
        return String::new();
    };
    let mut out = String::new();
    for line in text.lines() {
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn render_object(spec: &ir::Ir, nt: &ir::NamedType, o: &ir::ObjectType) -> String {
    let name = named_ref(nt);
    let mut s = String::new();
    s.push_str(&doc_comment(nt.documentation.as_deref()));
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    s.push_str(&format!("pub struct {name} {{\n"));
    let mut used_field_idents: std::collections::HashSet<String> =
        std::collections::HashSet::new();
    for prop in &o.properties {
        s.push_str(&doc_comment(prop.documentation.as_deref()));
        let raw_name = &prop.name;
        let sanitised = rust_ident_snake(raw_name);
        // Disambiguate against earlier fields in the same struct. Two raw
        // names that sanitise to the same Rust ident (e.g. GitHub
        // Reactions' `+1` / `-1` both → `_1`) get `_2`, `_3`, … suffixes
        // until unique. The serde rename below preserves the wire name.
        let field = disambiguate(&sanitised, &mut used_field_idents);
        // Serde rename if the sanitized field name doesn't match the
        // original wire name. Strip a possible `r#` prefix when comparing.
        let field_compare = field.strip_prefix("r#").unwrap_or(&field);
        if field_compare != raw_name {
            s.push_str(&format!("    #[serde(rename = \"{}\")]\n", escape_str(raw_name)));
        }
        let mut ty = render_type_ref(spec, &prop.r#type);
        // Optional (not in `required`) wraps in Option<T> with skip_serializing_if.
        let is_required = prop.required;
        if !is_required {
            s.push_str("    #[serde(skip_serializing_if = \"Option::is_none\", default)]\n");
            // Avoid double-wrapping if the underlying type is already Option<T>
            // (i.e. a nullable required field is `Option<T>` already; an
            // optional-and-nullable field stays `Option<T>` — JSON Schema
            // can't distinguish "missing" from "null" here, and serde's
            // default + Option handles both).
            if !ty.starts_with("Option<") {
                ty = format!("Option<{ty}>");
            }
        }
        s.push_str(&format!("    pub {field}: {ty},\n"));
    }
    // additional_properties → flatten an open extras map.
    match &o.additional_properties {
        ir::AdditionalProperties::Forbidden => {}
        ir::AdditionalProperties::Any => {
            s.push_str("    #[serde(flatten)]\n");
            s.push_str(
                "    pub extras: std::collections::HashMap<String, serde_json::Value>,\n",
            );
        }
        ir::AdditionalProperties::Typed { r#type } => {
            let inner = render_type_ref(spec, r#type);
            s.push_str("    #[serde(flatten)]\n");
            s.push_str(&format!(
                "    pub extras: std::collections::HashMap<String, {inner}>,\n"
            ));
        }
    }
    s.push_str("}\n");
    s
}

fn render_array_alias(spec: &ir::Ir, nt: &ir::NamedType, a: &ir::ArrayType) -> String {
    let name = named_ref(nt);
    let inner = render_type_ref(spec, &a.items);
    let mut s = doc_comment(nt.documentation.as_deref());
    s.push_str(&format!("pub type {name} = Vec<{inner}>;\n"));
    s
}

/// "Is this object the canonical map shape?" — empty `properties` plus
/// `additional_properties: Typed { … }`. Returns the values type-ref
/// when true. Issue #109 collapsed `MapType` into this Object spelling.
fn as_map(o: &ir::ObjectType) -> Option<&ir::TypeRef> {
    if !o.properties.is_empty() {
        return None;
    }
    if let ir::AdditionalProperties::Typed { r#type } = &o.additional_properties {
        Some(r#type)
    } else {
        None
    }
}

fn render_map_alias(spec: &ir::Ir, nt: &ir::NamedType, values: &ir::TypeRef) -> String {
    let name = named_ref(nt);
    let inner = render_type_ref(spec, values);
    let mut s = doc_comment(nt.documentation.as_deref());
    s.push_str(&format!(
        "pub type {name} = std::collections::HashMap<String, {inner}>;\n"
    ));
    s
}

fn render_enum_string(nt: &ir::NamedType, e: &ir::EnumStringType) -> String {
    let name = named_ref(nt);
    let mut s = doc_comment(nt.documentation.as_deref());
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]\n");
    s.push_str(&format!("pub enum {name} {{\n"));
    let mut used: std::collections::HashSet<String> = std::collections::HashSet::new();
    // (variant_ident, wire_value) pairs — needed below for the Display impl.
    let mut variants: Vec<(String, String)> = Vec::with_capacity(e.values.len());
    for v in &e.values {
        s.push_str(&doc_comment(v.documentation.as_deref()));
        let sanitised = rust_ident_pascal(&v.value);
        let variant = disambiguate(&sanitised, &mut used);
        // Always emit the rename so the on-the-wire string is preserved
        // verbatim regardless of how PascalCase mangled it.
        s.push_str(&format!(
            "    #[serde(rename = \"{}\")]\n",
            escape_str(&v.value)
        ));
        s.push_str(&format!("    {variant},\n"));
        variants.push((variant, v.value.clone()));
    }
    s.push_str("}\n");

    // Display: write the wire value (the same string `serde(rename)` uses).
    // This is what makes the enum usable as a query / header / path param
    // value — see #48.
    s.push_str(&format!("impl std::fmt::Display for {name} {{\n"));
    s.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    if variants.is_empty() {
        s.push_str("        match *self {}\n");
    } else {
        s.push_str("        match self {\n");
        for (variant, wire) in &variants {
            s.push_str(&format!(
                "            Self::{variant} => f.write_str(\"{}\"),\n",
                escape_str(wire)
            ));
        }
        s.push_str("        }\n");
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

fn render_enum_int(nt: &ir::NamedType, e: &ir::EnumIntType) -> String {
    let name = named_ref(nt);
    let repr = match e.kind {
        ir::IntKind::Int32 => "i32",
        ir::IntKind::Int64 => "i64",
    };
    let mut s = doc_comment(nt.documentation.as_deref());
    s.push_str("#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]\n");
    s.push_str(&format!("#[repr({repr})]\n"));
    s.push_str(&format!("pub enum {name} {{\n"));
    let mut used: std::collections::HashSet<String> = std::collections::HashSet::new();
    for v in &e.values {
        s.push_str(&doc_comment(v.documentation.as_deref()));
        // Variant name like `V42` for 42 — legal Rust ident, prefixed so
        // negatives stay parseable.
        let raw = if v.value < 0 {
            format!("Neg{}", -v.value)
        } else {
            format!("V{}", v.value)
        };
        let variant = disambiguate(&raw, &mut used);
        s.push_str(&format!("    {variant} = {},\n", v.value));
    }
    s.push_str("}\n");

    // Display: dispatch through the underlying integer so `to_string()`
    // produces the wire value used in URL contexts (#48). `*self as <repr>`
    // works because the enum is `Copy` + `#[repr(<repr>)]`.
    s.push_str(&format!("impl std::fmt::Display for {name} {{\n"));
    s.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    s.push_str(&format!("        (*self as {repr}).fmt(f)\n"));
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

fn render_union(spec: &ir::Ir, nt: &ir::NamedType, u: &ir::UnionType) -> String {
    let name = named_ref(nt);
    let mut s = doc_comment(nt.documentation.as_deref());
    // Multi-variant unions containing Null render the enum body without
    // the Null arm; consumers of the named type wrap with `Option<>` via
    // [`render_type_ref`]'s `union_has_null` check. Issue #107.
    let visible_variants: Vec<&ir::UnionVariant> = u
        .variants
        .iter()
        .filter(|v| !forge_plugin_sdk::is_null_typeref(&spec.types, &v.r#type))
        .collect();
    if let Some(disc) = &u.discriminator {
        s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        s.push_str(&format!(
            "#[serde(tag = \"{}\")]\n",
            escape_str(&disc.property_name)
        ));
        s.push_str(&format!("pub enum {name} {{\n"));
        let mut used: std::collections::HashSet<String> = std::collections::HashSet::new();
        for v in &visible_variants {
            let variant_type = render_type_ref(spec, &v.r#type);
            let tag = v.tag.as_deref().unwrap_or(&variant_type);
            let sanitised = rust_ident_pascal(tag);
            let variant_name = disambiguate(&sanitised, &mut used);
            if tag != variant_name.as_str() {
                s.push_str(&format!("    #[serde(rename = \"{}\")]\n", escape_str(tag)));
            }
            s.push_str(&format!("    {variant_name}({variant_type}),\n"));
        }
        s.push_str("}\n");
    } else {
        // Untagged unions are deferred (issue #26). Emit a placeholder
        // so the file still parses; the generator-level diagnostic
        // belongs in `emit::all`. For v1 we simply union the variants
        // with `serde(untagged)`.
        s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        s.push_str("#[serde(untagged)]\n");
        s.push_str(&format!("pub enum {name} {{\n"));
        for (i, v) in visible_variants.iter().enumerate() {
            let variant_type = render_type_ref(spec, &v.r#type);
            s.push_str(&format!("    Variant{i}({variant_type}),\n"));
        }
        s.push_str("}\n");
    }
    s
}

/// Append `_2`, `_3`, … to `name` until it isn't already in `used`, then
/// insert it. Used inside a single struct/enum to disambiguate
/// fields/variants whose raw names sanitise to the same Rust ident
/// (#49). The serde rename on the parent declaration preserves the wire
/// name regardless of which suffix we chose.
fn disambiguate(name: &str, used: &mut std::collections::HashSet<String>) -> String {
    if !used.contains(name) {
        used.insert(name.to_string());
        return name.to_string();
    }
    let mut n: u32 = 2;
    loop {
        let candidate = format!("{name}_{n}");
        if !used.contains(&candidate) {
            used.insert(candidate.clone());
            return candidate;
        }
        n += 1;
    }
}

fn escape_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}
